agg_function_name: sum
aggregator_kwargs: {}
aggregator_name: nra_w_impute
dataset_kwargs:
  combine_sales: true
dataset_name: vgsales
imputer_kwargs:
  hidden_layer_sizes:
  - 64
  - 64
  - 64
  - 64
  max_iter: 1000
  use_cache: true
  verbose: false
imputer_name: ml
k:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 15
- 20
output_path: outputs/sales_only/vgsales_combined_nra_impute
p_erase: 0
scorer_kwargs:
  columns_to_drop:
  - earliest_year
  - num_platforms
  normalize: true
seed: 42
