agg_function_name: avg
aggregator_kwargs: {}
aggregator_name: nra
dataset_kwargs: {}
dataset_name: toy2
imputer_kwargs: {}
imputer_name: basic
k: 2
output_path: outputs/toy_nra
p_erase: 0
scorer_kwargs: {}
seed: 42
